# docker run -p 9090:9090 -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'klite_sample'
    static_configs:
      - targets: ['192.168.0.68:8080'] # Replace with host IP
